# Generated by Django 6.0 on 2026-01-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enhanced_beauty_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='preference_note',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_ink_color',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_needle_type',
        ),
    ]
