# Generated by Django 5.2.9 on 2026-05-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enhanced_beauty_api', '0003_availability_service_description_service_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'Availabilities'},
        ),
    ]
