# Generated by Django 5.2.9 on 2026-05-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhanced_beauty_api', '0004_alter_availability_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enhanced_beauty_api.availability'),
        ),
    ]
