# Generated by Django 5.2.9 on 2026-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhanced_beauty_api', '0005_alter_booking_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='location',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
